### ISSUE TITLE
NAVIGATION_5: Consistent H1 and H2 page section labels

### ISSUE THREAD

**Issue by opena11y** [opena11y/oaa-rules#11]
Desc: Same issue as HEADING_1 when page has no H1
Data: "page: no page title" in Element column of Element Results table

Tool: AInspector Sidebar
Evaluation Library Version: 0.9.7.3
Ruleset: HTML4 Legacy Techniques
URL: https://news.ycombinator.com/

**Comment by jongund** [comment]
Removed "no title found", I think it is better for it to be simple "page"
