### ISSUE TITLE
TITLE_2: H1 must/should match part of the TITLE

### ISSUE THREAD

**Issue by opena11y** [opena11y/oaa-rules#12]
Desc: Same issue as HEADING_1 when page has no H1
Data: "page: no page title" in Element column of Element Results table

Tool: AInspector Sidebar
Evaluation Library Version: 0.9.7.3
Ruleset: HTML4 Legacy Techniques
URL: https://news.ycombinator.com/

**Comment by jongund** [comment]
Updated TITLE rule 2, it had a number of issues including not being very forgiving for more than 2 visible H1 elements
1. updated messaging for checking title with up to 2 H1 elements for consistency of H1 content with TITLE content
2. If more than 2 visible H1 elements the rule returns a manual check for verifying the H1 elements identify and describe a major section of the page, this clause though creates a mismatch with the rule summary and description

**Comment by jongund** [comment]
Remove rule from rulesets.  The rule has problems when there are more that 2 H1 elements on the page.
