### ISSUE TITLE
New Rule: Headings must be explicit

### ISSUE THREAD

**Issue by A11YAngel** [opena11y/oaa-rules#20]
**Current Category**: Headings
**New Rule**: Headings must be explicit
**Requirement or recommendation**:  Required

**Purpose/description**: 
Explicit headings that are tagged with heading elements such as h1 to h6 help users of screen readers navigate from heading to heading within the page or use a feature in screen readers to pull up a list of explicit headings. Without the heading elements, screen reader users will not be able to find explicit headings. Also when the style sheets are turned off, the meaning of implicit headings gets lost. Implicit headings imply meaning visually is based on the style such as bold, color, font size, background color, etc.

HTML heading elements such as h1 to h6 must be used to mark up page content that visually appears as a heading.

**Standards**:
§ 508-1194.22|
(d) Documents shall be organized so they are readable without requiring an associated style sheet.
WCAG 1.0 Priority 2
3.5 Use header elements to convey document structure
WCAG 1.0 Priority 2
12.3 Divide large blocks of info into more manageable groups
WCAG 2.0 Level A
1.3.1 Information and Relationships
WCAG 2.0 Level A
2.4.6 Headings and Labels

**Comment by jongund** [comment]
We have 9 rules and a headings category and so I think there is an implied message of the  importance and use in accessible web design.   I don't think a page level manual check will make increase importance or awareness to developers of using headers for accessibility.
