### ISSUE TITLE
New Category: Lists and New Rule: List markup must be explicit

### ISSUE THREAD

**Issue by A11YAngel** [opena11y/oaa-rules#22]
**New Category**: Lists
**New Rule**:  List markup must be explicit
**Requirement or recommendation**:  Recommended
There is no standard for the list markup available in Section 508 so this is highly recommended to ensure that the list markup is explicit to users of screen readers.

**Purpose/description**: 
Lists that appear to be implicit without the proper list markup. Common practices involve tables that list items, visually indented list (without list markup) or bullet or image that marks each list item visually as a list.

A proper list structure helps users of assistive technologies like screen readers understand the hierarchical structure and position of list items. This structure helps them determine the number of list items in the list and the list hierarchy of nested lists as well.

**Standards**:
WCAG 1.0 Priority 2
3.6 Mark up lists and list items properly
WCAG 2.0 Level A
1.3.1 Information and Relationships

**Comment by jongund** [comment]
List rule 1 and 2 address the use of list markup
