### ISSUE TITLE
New Category: Page Structure and New Rule: Reading order must be logical

### ISSUE THREAD

**Issue by A11YAngel** [opena11y/oaa-rules#26]
**New Category**: Page Structure
I do not think that this new rule should be placed under "Styling/Content" category. Page Structure is more appropriate for this new rule.
**New Rule**:  Reading order must be logical
**Requirement or recommendation**:  Required

**Purpose/description**: 
Assistive technologies such as screen readers typically follow the order of the source code regardless of the methods (i.e., CSS) used to imply the visual reading order or layout. This happens when the reading order becomes illogical or does not make sense to users using assistive technologies.  
Within the source code, the sequential reading order of the markup and text must reflect the visual reading order or layout of the page content that makes sense. To ensure that the reading order or layout is logical is to follow the default reading order of the English language from top to bottom and left to right.

**Standards**:
§ 508-1194.22
(d) Documents shall be organized so they are readable without requiring an associated style sheet.
WCAG 1.0 Priority 1
6.1 Readable docs that make sense without style sheets
WCAG 1.0 Priority 2
5.3 Proper linearized layout tables
WCAG 2.0 Level A
1.3.2 Meaningful Sequence

**Comment by jongund** [comment]
We currently have two rules related to reading order:
http://fae20.cita.illinois.edu/rule/rc/LAYOUT_1/ 
http://fae20.cita.illinois.edu/rule/rc/FOCUS_1/ 

Are you proposing a more general rule that would appear on any page?
Are there certain features of a page that you have seen that cause problems (i.e use of absolute positioning).   We are trying to avoid having manual checks that are not triggered by some feature on the page.

**Comment by A11YAngel** [comment]
Tab/focus order and reading order are two different things. Tab/focus order focuses on the active elements in the tab order given. Reading order occurs when users of screen readers use the arrow keys for reading the content.

I have seen a few that were affected by the reading order in recent evaluations. Violations are often found by manual checking. I will need to go back and find them.

Manual checking is always required no matter what automated testing tools could or could not do for you. Expect to see new rules that require manual checking.

**Comment by jongund** [comment]
How many times if the focus order is good in the reading order bad?

**Comment by A11YAngel** [comment]
Let’s discuss this when you get back.

There is a difference between focus/tab order and reading order. Focus order is for those active elements in the logical tab order only while the reading order is for the content that is read from left to right and top to bottom in English language in the logical order only; this has nothing to do with the active elements in the page or content structure.  I know this can be confusing or hard for some people to understand the difference between those two. It is so important to keep tab order and reading order apart when we look for things during the manual checking. This is why the reading order is under the new category, Page Structure or Content Structure.

Please keep in mind that I know a lot of rules in my head that we do not have available here especially for manual checking (evaluation techniques).

**Comment by A11YAngel** [comment]
Jon,

I found a perfect example on reading order from Liam’s report via Wiki. I advised Liam to correct the reading order in the source code of his web application.

Here is the problem I found:
When reading the content with arrow keys via screen readers, the reading order follows the order of the source code rather than the visual order or layout. Typically, the default (and visual) order is normally read from left to right and top to bottom in English language. For example:
Typical visual order:

  1.  Navigation section
  2.  Main content section
  3.  Transcript section
Source code in this order:

  1.  Navigation section
  2.  Footer section (Transcript)
  3.  Main content section
Here is what I suggested for remediation:
Proper reading order can be achieved by rearranging the source code:
Order of source code must be:

  1.  Navigation section
  2.  Main content section
  3.  Transcript section
Hope this helps!

Regards,

Lori

From: Lane, Lori
Sent: Tuesday, April 07, 2015 10:17 AM
To: 'opena11y/oaa-rules'
Subject: RE: [oaa-rules] New Category: Page Structure and New Rule: Reading order must be logical (#26)

Let’s discuss this when you get back.

There is a difference between focus/tab order and reading order. Focus order is for those active elements in the logical tab order only while the reading order is for the content that is read from left to right and top to bottom in English language in the logical order only; this has nothing to do with the active elements in the page or content structure.  I know this can be confusing or hard for some people to understand the difference between those two. It is so important to keep tab order and reading order apart when we look for things during the manual checking. This is why the reading order is under the new category, Page Structure or Content Structure.

Please keep in mind that I know a lot of rules in my head that we do not have available here especially for manual checking (evaluation techniques).

**Comment by A11YAngel** [comment]
Jon,

Your question: 

For your proposed document linearization rule, what are the testing procedures you would recommend people use to verify the document reading order complies with WCAG requirements?

What I do for the testing procedures for Reading Order:

1) Look for elements positioned in a logical reading order by turning off colors and images in Internet Explorer

•     Tools > Internet Options > Accessibility > Select “Ignore colors specified on webpages”

Does the reading order makes sense when the colors and images are disabled? It is more likely not. This causes disorientation or confusion for users with low vision. 

2) Look for elements positioned in a logical order via CSS positioning of elements or HTML code

•     Use screen readers to test for reading order using arrow keys

Examples:
• One of the examples is when visible links are positioned in the bread crumb area of the web page using CSS, but they are actually positioned at the bottom of the source code. 
• Another example of illogical reading order occurs when the HTML structural elements are not in logical order. The visual reading order must match the order of the source code. This can be achieved by rearranging the source code to match the visual reading order. 

     Logical visual reading order: Header, Main, Footer
     Illogical source code: Header, Footer, Main

• Layout table is another example that affects the reading order of the layout table. Layout tables are used for visual effect based on the source code. Screen readers read from left to right and top to bottom linearly following the source code rather than the visual order of layout tables. 

These examples above cause disorientation and confusion for blind users using screen readers. 

“Reading Order” is familiarized by most people than “linear order” and this also helps differentiate between Tab Order and Reading Order than “linear order”. Linear order is too general and can be confusing when people want to talk about Tab Order or Reading Order specifically. 

Also people have referred to Tab Order the same as Focus Order as well. 

Hope this helps!

Lori

**Comment by jongund** [comment]
I have added reading order rule 1 to version 0.9.9.2 of the evaluation library
