### ISSUE TITLE
New Category: Frames and New Rule: Frame titles must be descriptive

### ISSUE THREAD

**Issue by A11YAngel** [opena11y/oaa-rules#27]
**New Category**: Frames
**New Rule**:  Frame titles must be descriptive
**Requirement or recommendation**:  Required

**Purpose/description**: 
Without the iframe title or textual information, screen readers will search for other nearby information such as the file name to compensate for the missing iframe title. This will confuse users when inappropriate information does not make sense or does not reflect its purpose of the iframe. Also users will have difficulty navigating between frames when they look for the page content.

Useful page content: Ensure that the frames are given a meaningful and concise name by using aria-label attribute. Describe what the purpose or action of the iframe does. 

Empty or unused frames: Provide aria-hidden attribute that will be ignored by screen readers. For example:

frame aria-hidden="true"...

The other option is to remove the frame from the DOM until used or needed.

**NOTE**: We had this discussion in meeting yesterday (3/16/15) about iframe and ARIA attributes, but after careful analysis, shouldn’t we be still using title attribute for older screen readers and browsers? I am concerned that older technologies will not be able to render ARIA attributes. Please advise. Thanks. 

**Standards**:
§ 508-1194.22
(i) Proper frame identification and navigation
WCAG 1.0 Priority 1
12.1 Frame titles
WCAG 2.0 Level A
2.4.1 Bypass Blocks
WCAG 2.0 Level A
4.1.2 Name, Role, Value

**Comment by jongund** [comment]
frame rules added to version 0.9.9.2 of ruleset
