### ISSUE TITLE
New Rule: SkipTo link target must be present and valid

### ISSUE THREAD

**Issue by A11YAngel** [opena11y/oaa-rules#35]
**Current Category**: Keyboard Support
**New Rule**: SkipTo link target must be present and valid
**Requirement or recommendation**:  Required

**Purpose/description**: 
As part of the SkipTo link mechanism, a SkipTo target must be present and valid within the page. The SkipTo target must be located at the beginning of any content (e.g., main content).

This happens a lot when developers forget to add this critical SkipTo target technique within the page. Without the SkipTo target, the SkipTo link mechanism will not function at all.

**Standards**:
§ 508-1194.22
(o) A method shall be provided that permits users to skip repetitive navigation links.
WCAG 2.0 Level A
2.4.1 Bypass Blocks

**Comment by jongund** [comment]
Already checks for a valid target
