### ISSUE TITLE
Empty heading elements

### ISSUE THREAD

**Issue by jongund** [opena11y/oaa-rules#36]
How should empty heading elements be treated in rules

**Comment by inspector508** [comment]
I think they should be treated as a violation, but that's just me.

**Comment by jongund** [comment]
Need to see if this was resolved, right now I think they should just be ignored for evaluation

**Comment by jongund** [comment]
We currently mark these headings as hidden, so they can be found (e.g. viewed in a list of headings)  but have not effect on accessibility evaluation
