### ISSUE TITLE
Minor mispelling, syntax, and HTML coding issues

### ISSUE THREAD

**Issue by kensgists** [opena11y/oaa-rules#40]
In reading through the development version of the rules pages, I stumbled across some minor, easily fixable, misspelling, syntax, and HTML coding errors:

* http://fae20-dev.cita.illinois.edu/rulesets/ARIA_TRANS/sc/Rule/ERROR_1/, under Techniques, "aria-invalid" is misspelled.
* http://fae20-dev.cita.illinois.edu/rulesets/ARIA_TRANS/sc/Rule/TABLE_7/, under Purpose, "cannot be relied to provide header information." should be "relied upon..."
* http://fae20-dev.cita.illinois.edu/rulesets/ARIA_TRANS/sc/Rule/HEADING_1/, under Purpose, "could be considered having some what equal" should be ".. somewhat..."
* http://fae20-dev.cita.illinois.edu/rulesets/ARIA_TRANS/sc/Rule/VIDEO_1/, under Purpose, "means for people cannot see the video to understand the video content" should be "... people who ..."
* http://fae20-dev.cita.illinois.edu/rulesets/ARIA_TRANS/sc/Rule/ERROR_4/, under Purpose, "Users benefit from information being informed of invalid information and on how to correct invalid input." has redundancies and/or syntax issues
http://fae20-dev.cita.illinois.edu/rulesets/ARIA_TRANS/sc/Rule/ROLE_3/ has improper HTML for identifying the \<code\> elements

**Comment by jongund** [comment]
Edits have been made in version 0.9.9.2.

Thank you for the feedabck and edits
