### ISSUE TITLE
LINK_4: Link text must be descriptive

### ISSUE THREAD

**Issue by opena11y** [opena11y/oaa-rules#6]
Desc: The following substring was found in the ACTIONS V message
Data: %1 links

Tool: AInspector Sidebar
Evaluation Library Version: 0.9.7.3
Ruleset: HTML4 Legacy Techniques
URL: http://www.washingtonpost.com/

**Comment by opena11y** [comment]
In the NLS file JS code, the %1 is not surrounded by double quotes (i.e., should be "%1").

**Comment by jongund** [comment]
Changed %1 to %N_F in action message

**Comment by jongund** [comment]
Added HIDDEN_P and HIDDEN_S messages to rule
