### ISSUE TITLE
Long description for images: how do 'alt' and 'title' affect each other?

### ISSUE THREAD

**Issue by nhoyt** [opena11y/oaa-rules#62]
Rule: Long description for complex images
Desc: In the TECHNIQUES section we point out that the 'title' attribute can be used for a long description. Is there an interaction between 'title' and 'alt' (e.g., does one take precedence over the other)?
Tool: N/A
Evaluation Library Version: 1.0.0-beta.2
URL: N/A

**Comment by jongund** [comment]
added test for alt text same or similar to title attribute content

**Comment by jongund** [comment]
included in Version 1.0.0-beta-5
