### ISSUE TITLE
FOCUS_5: Forms submitted using buttons

### ISSUE THREAD

**Issue by opena11y** [opena11y/oaa-rules#7]
In the Firefox Browser Console, the following error is reported:
ReferenceError: reference to undefined property de.role

Tool: AInspector Sidebar
Evaluation Library Version: 0.9.7.3
Ruleset: HTML4 Legacy Techniques
URL: http://www.relegant.com/current-events/

**Comment by opena11y** [comment]
The console links to this code on line 384 of rules_focus.js:
if (de.role === "button") {

**Comment by jongund** [comment]
FIxed bug by providing a default value of empty string for de.role and using the de.has_role property in focus rule 5
