### ISSUE TITLE
HEADING_1: Page must/should have H1 element

### ISSUE THREAD

**Issue by opena11y** [opena11y/oaa-rules#8]
Desc: In the Element Results table, when a page does not have an H1 element (rule result is W), the Element column displays the following:
Data: "page: no page title"

Is this correct, when a page does in fact have a TITLE element (in this case: "Hacker News"), or is this an issue related to not wanting to display element properties in the Element column? If we are choosing not to display the page title, we should probably get rid of the "no page title" part.

Tool: AInspector Sidebar
Evaluation Library Version: 0.9.7.3
Ruleset: HTML4 Legacy Techniques
URL: https://news.ycombinator.com/

**Comment by jongund** [comment]
Removed "no title found", I think it is better for it to be simple "page", there should be no referent to "title" in this rule
