### ISSUE TITLE
NAVIGATION_1: At least two ways of finding content

### ISSUE THREAD

**Issue by opena11y** [opena11y/oaa-rules#9]
Desc: Same issue as HEADING_1 when page has no H1
Data: "page: no page title" in Element column of Element Results table

Tool: AInspector Sidebar
Evaluation Library Version: 0.9.7.3
Ruleset: HTML4 Legacy Techniques
URL: https://news.ycombinator.com/

**Comment by jongund** [comment]
removed "no page title", so just says "page", I think this is better for the rule
