### ISSUE TITLE
Rule for manual check for accessible descriptions

### ISSUE THREAD

**Issue by jongund** [opena11y/oaa-rules#92]
title attribute is being abused on link elements, so may want a manual check for lmage descriptions

**Comment by A11YAngel** [comment]
And on non-link elements (e.g., images). Some titles derive from file names such as “meas-eval-servicebanner”

**Comment by jongund** [comment]
Worried about having such a specific rule about misuse of title on an image.  Maybe this type issues is better highlighted in a visualization tool.
